name: pdf-build

on:
  push:
    paths:
      - documentation/**

jobs:
  md2pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Build documentation via Docker image
        run: >
          find -name '*.md' |
          parallel docker run --rm -v $(pwd):/data -u $(id -u):$(id -g) detjensrobert/arch-pandoc -V geometry:margin=1in --highlight=tango -s {} -o {.}.pdf
        working-directory: ./documentation

      - name: Commit built PDFs
        uses: EndBug/add-and-commit@v7
        with:
          add: '*.pdf'
          default_author: github_actions
          message: Build documentation
